### ISSUE TITLE
특정 문자 미노출 현상

### ISSUE THREAD

**Issue by freakyimac** [sun-typeface/SUIT#11]
안녕하세요 suit 폰트가 너무 마음에 들어서 사용 검토중에 있습니다. 멋진 폰트 공유에 감사드립니다. 🙇🏻‍♂️ iOS 앱에 폰트 적용 시(v1.2.5) 특정 문자들이 노출되지 않는 것 같아서 문의드려요. 해당 현상은[font preview 기능을 제공하는 타 플랫폼](https://eng.fontke.com/family/1614895/style/)(Web)에서도 확인되었으며, [suit 공식 홈페이지](https://sun.fo/suite/)에서는 해당 문자들만 굵기가 정상적으로 적용되지 않는 것으로 확인되었습니다

![IMG_7981](https://github.com/sun-typeface/SUIT/assets/131536209/0e240650-39ed-4a44-baf7-721a44899f80)

![IMG_7979](https://github.com/sun-typeface/SUIT/assets/131536209/2abd9019-999c-4253-baa5-8bd26795f7f7)

**Comment by sun-typeface** [comment]
안녕하세요.

말씀주신 "핯핲핮"의 경우 일반적인 한국 표준어 표기에서 사용 되지 않는 글자로 SUIT, SUITE 배포본에 포함되어 있지 않습니다.

SUIT, SUITE의 경우 임베딩을 목적으로 만들어져 완성형 2,350자와 외래어 및 신조어 표현을 위한 318자만 포함되어 있어 otf, ttf의 경우 포함되지 않은 글자는 공백으로 표시되며, woff의 경우 시스템 기본 폰트로 대체되어 표시되도록 되어 있어 첨부해주신 스크린샷처럼 굵기가 적용되지 않은 상태로 표시되게 됩니다.

혹시 사용하시고자 하는 환경에서 외래어등의 표기로 인해 특이한 글자가 필요하신 경우 다시 리포트해주시면 다음 배포본에서 해당 글자를 포함하는 것을 검토하도록 하겠습니다. 잘 사용해주셔서 감사드립니다. :-)
